version: "3.9"

services:
  whatsapp-bot-baileys:
    container_name: whatsapp-bot-baileys
    build: .
    restart: unless-stopped
    volumes:
      - ./auth_info_baileys:/usr/src/app/auth_info_baileys
    tty: true
